### PR TITLE
Use Networking API instead of Extensions for Ingress

### PR DESCRIPTION
**Pull request by mikkeloscar**
Updates all cases of Ingress interaction to use the newer `networking.k8s.io/v1beta1` apiVersion instead of `extensions/v1beta1`

This also updates the Autoscaling config to create HPA with ingress type pointing to the `networking.k8s.io/v1beta1` api. This is supported since https://github.com/zalando-incubator/kube-metrics-adapter/releases/tag/v0.1.5

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
@mikkeloscar Please update the VERSION, and readme to clarify which K8s version is required from the new version on.

**Comment by mikkeloscar** [comment]
Bumped version and added a short section on Kubernetes compatibility to the README.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
