### PR TITLE
Use a much higher QPS values for E2E

### PR DESCRIPTION
**Pull request by aermakov-zalando**
The defaults are super low, and lead to either E2E taking a ton of time or to occasional failures. Increase to more sensible values.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by aryszka** [comment]
:+1:

**Comment by jonathanbeber** [comment]
what were the default values?

**Comment by aermakov-zalando** [comment]
5 RPS with a 10 request burst.

**Pull request merged**
