### PR TITLE
Build with CDP overlay

### PR DESCRIPTION
**Pull request by mikkeloscar**
Enable CDP build and use CDP overlay instead of drone based build.

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
@szuecs looks like your approval comment is not accepted by zappr :( I think you need to write :+1: in a "normal" comment.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
