### PR TITLE
Stack's RouteGroups inherit annotations

### PR DESCRIPTION
**Pull request by jonathanbeber**
The RouteGroups generated per Stack are not receiving the annotations
from StackSet's RouteGroups definition. It can lead to a wide range of
bug reports and is a non-expected behaviour.

This commit adds the procedure to copy the annotations from the
StackSet's RouteGroups spec and tests.

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
👍

**Comment by jonathanbeber** [comment]
:+1:

**Comment by jonathanbeber** [comment]
where are the e2e tests? :/

**Comment by muaazsaleem** [comment]
> where are the e2e tests? :/
@jonathanbeber https://github.com/zalando-incubator/stackset-controller/tree/master/cmd/e2e

**Comment by jonathanbeber** [comment]
> > where are the e2e tests? :/
> > @jonathanbeber https://github.com/zalando-incubator/stackset-controller/tree/master/cmd/e2e

haha, sorry, it was because CDP didn't start the pipeline, that's why I closed and reopened the PR. Now it's running!

**Comment by mikkeloscar** [comment]
:+1:

**Comment by jonathanbeber** [comment]
:+1:

**Pull request merged**
