### PR TITLE
Drop support for traffic management via Ingresses

### PR DESCRIPTION
**Pull request by aermakov-zalando**
We've migrated to stackset-based traffic management and don't intend to migrate back. Let's just drop the unnecessary code.

### CODE REVIEW

**Comment by muaazsaleem** [comment]
👍

**Comment by mikkeloscar** [comment]
FYI: I changed the version bump from `v2.0` to `v1.3` i.e. just bumping the minor version. I think this is the right way because while I understand that we change the API a bit, we're not doing major changes overall to StackSet which would prompt a v2 in my mind.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by muaazsaleem** [comment]
👍

**Pull request merged**
