### PR TITLE
Add a health check with last time of sync

### PR DESCRIPTION
**Pull request by linki**
This adds an extensible health check endpoint as well as an initial check for the last sync time.

The output can be seen at `http://127.0.0.1:7979/healthz?full=1`.

This particular check starts out unhealthy and switches to healthy for as long as the last sync interval isn't missed for too long (this code sets it to two intervals).

This can be used
* in a `readinessProbe` to ensure the initial sync succeeds, as well as
* in a `livenessProbe` to restart stackset-controller in case it gets stuck

### CODE REVIEW

**Comment by aermakov-zalando** [comment]
It'll still be healthy before the first `Run` starts, might want to add a dummy failed check when registering.

**Comment by linki** [comment]
I moved registration of `/healthz` to after `startWatch()` is called. This should avoid any false positives during initial bootstrap.

**Comment by aermakov-zalando** [comment]
Could you rebase on master? I've fixed the e2e deployment.

**Comment by aermakov-zalando** [comment]
Otherwise LGTM.

**Comment by linki** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Pull request merged**
