### PR TITLE
Updating golangci

### PR DESCRIPTION
**Pull request by njuettner**
Only updating golangci version

### CODE REVIEW

**Comment by mikkeloscar** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Comment by mikkeloscar** [comment]
@njuettner I changed some things to make it run on travis. For some reason it takes more than a minute to execute `golangci-lint` in travis, so I had to increase the `timeout` from `1m` to `2m`. Not sure what is the reason. but now it works.

**Comment by mikkeloscar** [comment]
:+1:

**Comment by szuecs** [comment]
:+1:

**Pull request merged**
